### ISSUE TITLE
Query over installation

### ISSUE THREAD

**Issue by ashwgupt** [hosie/integration-dashboard#2]
Hi,
I am getting the error for Proxy setup when trying to install the package.

$npm install
npm ERR! network getaddrinfo ENOTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

That can be done but as I work in a very restircted environment, am very keen to know why exactly is the proxy setting required for. What material, if any, is downloaded/uploaded to internet during this installation. A clear reason will help me take it forward for use.

Thanks in advance!
-Ashwin

**Comment by hosie** [comment]
I have updated the install instructions.  Please open another issue if you still have problems
